import Header from './components/Header'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header/>
        <div className="container mx-auto md:px-0 px-3">
          {children}
        </div>
      </body>
    </html>
  )
}
